---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.devops.apps"
  name: "hubot-notifier"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      project: "${project.artifactId}"
      group: "io.fabric8.devops.apps"
  template:
    metadata:
      labels:
        provider: "fabric8"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.devops.apps"
    spec:
      containers:
      - env:
        - name: "HUBOT_KUBERNETES_ROOM"
          value: "#fabric8_${namespace}"
        - name: "HUBOT_USERNAME"
          valueFrom:
            configMapKeyRef:
              key: "hubot-username"
              name: "hubot-notifier"
        - name: "HUBOT_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "hubot-password"
              name: "hubot-notifier"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/hubot-notifier:${project.version}"
        name: "hubot-notifier"
        ports:
        - containerPort: 8778
          name: "jolokia"
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
      serviceAccountName: "fabric8"
